[package]
name = "valve-gsi"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "valve-gsi"
path = "src/bin.rs"

[dependencies]
tiny_http = "0.11.0"
serde = {version = "1.0.136", features = ["derive"]}
serde_json = "1.0.79"